# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9db4ac27-e25a-4afa-94a2-9d835133a6c5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9db4ac27-e25a-4afa-94a2-9d835133a6c5".device = "/dev/disk/by-uuid/9db4ac27-e25a-4afa-94a2-9d835133a6c5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/17DA-68EE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-5753cf4a-fcda-42e7-983a-942c37f2af2f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
